# Generated by Django 3.2 on 2021-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chokepoint',
            fields=[
                ('chokepoint_id', models.IntegerField(primary_key=True, serialize=False)),
                ('strait_name', models.CharField(blank=True, max_length=50, null=True)),
                ('alpha', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chokepoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChokepointRisk',
            fields=[
                ('chokepoint_risk_id', models.IntegerField(primary_key=True, serialize=False)),
                ('strait_name', models.CharField(blank=True, max_length=50, null=True)),
                ('chokepoint_risk', models.FloatField(blank=True, null=True)),
                ('year', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'chokepoint_risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CommodityLvh',
            fields=[
                ('commodity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('lvh', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'commodity_lvh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Corridor',
            fields=[
                ('corridor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('corridor_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('load_country', models.CharField(blank=True, max_length=20, null=True)),
                ('load_port', models.CharField(blank=True, max_length=20, null=True)),
                ('discharge_port', models.CharField(blank=True, max_length=20, null=True)),
                ('discharge_country', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'corridor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorridorCk',
            fields=[
                ('corridor_ck_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'corridor_ck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorridorFailure',
            fields=[
                ('corridor_failure_id', models.IntegerField(primary_key=True, serialize=False)),
                ('corridor_failure_captive', models.FloatField(blank=True, null=True)),
                ('corridor_failure_no_captive', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corridor_failure',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorridorIntake',
            fields=[
                ('corridor_intake_id', models.IntegerField(primary_key=True, serialize=False)),
                ('intake', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corridor_intake',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorridorPipeline',
            fields=[
                ('corridor_pipeline_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'corridor_pipeline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorridorSeabranch',
            fields=[
                ('corridor_seabranch_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'corridor_seabranch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorridorWeight',
            fields=[
                ('corridor_weight_id', models.IntegerField(primary_key=True, serialize=False)),
                ('corridor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('relative_weight', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'corridor_weight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryChokepoint',
            fields=[
                ('country_ck_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'country_chokepoint',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CountryPipeline',
            fields=[
                ('country_pipeline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'country_pipeline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalRisk',
            fields=[
                ('loadcountry', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('averagefailure', models.CharField(blank=True, max_length=10, null=True)),
                ('totalintake', models.CharField(blank=True, max_length=10, null=True)),
                ('finalrisk', models.CharField(blank=True, max_length=10, null=True)),
                ('commodity', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'final_risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeoRisk',
            fields=[
                ('country', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('sea_risk', models.FloatField(blank=True, null=True)),
                ('geo_risk', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geo_risk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('pipeline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_length', models.FloatField(blank=True, null=True)),
                ('share_val', models.FloatField(blank=True, null=True)),
                ('load_port', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pipeline',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PiracyIndex',
            fields=[
                ('country', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('piracy', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'piracy_index',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wgi',
            fields=[
                ('country', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('voice_accountability', models.FloatField(blank=True, null=True)),
                ('political_stability', models.FloatField(blank=True, null=True)),
                ('gov_effectiviness', models.FloatField(blank=True, null=True)),
                ('regulatory_quality', models.FloatField(blank=True, null=True)),
                ('rule_of_law', models.FloatField(blank=True, null=True)),
                ('control_of_corruption', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'wgi',
                'managed': False,
            },
        ),
    ]
